apiVersion: v1
kind: ConfigMap
metadata:
  name: workloads-csv
  namespace: {{ .Release.Namespace }}
data:
  workloads.csv: |
{{ .Files.Get "workloads/workloads.csv" | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: replayer
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-writer
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create","get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-writer
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: replayer
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: job-writer
---
apiVersion: batch/v1
kind: Job
metadata:
  name: workloads-replayer
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      serviceAccountName: replayer
      restartPolicy: Never
      containers:
        - name: replayer
          image: {{ .Values.replayer.image | default "docker.io/goncaloferreirauva/workload-replayer:latest" | quote }}
          env:
            - name: WORKLOAD_NS
              value: "workloads"
          volumeMounts:
            - { name: data, mountPath: /data }
      volumes:
        - name: data
          configMap:
            name: workloads-csv
      ttlSecondsAfterFinished: 60
