apiVersion: batch/v1
kind: Job
metadata:
  name: workloads-replayer
  namespace: workloads
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata: {}
    spec:
      serviceAccountName: replayer
      restartPolicy: Never
      containers:
        - name: replayer
          image: workload-replayer:local
          imagePullPolicy: IfNotPresent
          env:
            - name: WORKLOAD_NS
              value: "workloads"
            - name: TARGET_SCHEDULER_NAME
              value: "ci-aware"
            - name: ENABLE_PROM_SIDECAR
              value: "false"
            - name: PROM_SIDECAR_IMAGE
              value: "goncaloferreirauva/ciw-metrics-agent:latest"
            - name: SCHEDULER_LABEL
              value: "carbonscaler"
            - name: DEFAULT_MAX_DEFER_FRACTION
              value: "0.25"
            - name: MAX_JOBS
              value: "30"
            - name: SKIP_GPU_JOBS
              value: "true"
            - name: SCHEDULER_NAME
              value: "ci-aware"
          volumeMounts:
            - {name: data, mountPath: /data}
      volumes:
        - name: data
          configMap: {name: workloads-csv}
