apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-aware
  namespace: workloads
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-aware-job-editor
  namespace: workloads
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get","list","watch","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-aware-job-editor
  namespace: workloads
subjects:
  - kind: ServiceAccount
    name: ci-aware
    namespace: workloads
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: ci-aware-job-editor
